version: "3"

services:
  loki:
    image: grafana/loki:3.0.0
    command: "-config.file=/etc/loki/loki-config.yml"
    volumes:
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - monitoring

  gateway:
    image: nginx:latest
    depends_on:
      - loki
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - monitoring

  monitoring-fastapi-a:
    container_name: monitoring-a
    hostname: monitoring-a
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "python -m uvicorn app.cmd.api:app --proxy-headers --port 8000 --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - ./logs/monitoring-a:/var/log/containers
    networks:
      - monitoring

  monitoring-fastapi-b:
    container_name: monitoring-b
    hostname: monitoring-b
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "python -m uvicorn app.cmd.api:app --proxy-headers --port 8001 --host 0.0.0.0"
    ports:
      - "8001:8001"
    volumes:
      - ./logs/monitoring-b:/var/log/containers
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
      - ./config/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
