version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /var/log/containers/fastapi.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: INFO

loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: no

  uvicorn.error:
    handlers: [console, file]
    level: INFO
    propagate: no

  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: no

root:
  handlers: [console, file]
  level: INFO